title: "Data Science Portfolio"
subtitle: "A page with my projects of data science."
theme: jekyll-theme-minimal
logo: "https://avatars.githubusercontent.com/u/23095852?s=460&u=f812d7fa8405c5db9c9a814bf21725152622e368&v=4"